
# ==========================================
# Machine Definitions
# Speed Unit: Percentage (100 = 1.0x standard speed)
# Power Unit: Integer
# ==========================================

# --- The Player (Hand) ---
[[machines]]
id = "hand"
power = 0

# --- Automated Industry Complex (AIC) ---
# --- Resourcing ---

[[machines]]
id = "portable_originium_rig"
power = 0

[[machines]]
id = "electric_mining_rig"
power = 5

[[machines]]
id = "fluid_pump"
power = 5

[[machines]]
id = "electric_mining_rig_mk2"
power = 10

# --- Processing ---

[[machines]]
id = "refining_unit"
power = 5

[[machines]]
id = "shredding_unit"
power = 10

[[machines]]
id = "fitting_unit"
power = 10

[[machines]]
id = "moulding_unit"
power = 10

[[machines]]
id = "planting_unit"
power = 10

[[machines]]
id = "seed_picking_unit"
power = 10

# --- Assembly ---

[[machines]]
id = "gearing_unit"
power = 10

[[machines]]
id = "filling_unit"
power = 10

[[machines]]
id = "packaging_unit"
power = 30

[[machines]]
id = "reactor_crucible"
power = 10

[[machines]]
id = "grinding_unit"
power = 20
