# ==========================================
# Recipe Definitions
# id:         String snake_case
# by:         String snake_case
# time:       Integer time to craft
# out:        Integer number of items when crafting
# is_source:  Optional Bool 
# inputs:     Dictionary id: Integer
# outputs:    Dictionary id: Integer (usually this term isn't necessary)
# ==========================================

# --- The Player ---

# --- Crafting ---

[[recipes]]
id = "portable_originium_rig"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
originium_ore = 5

[[recipes]]
id = "electric_mining_rig"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
portable_originium_rig = 1
originium_ore = 5

[[recipes]]
id = "fluid_pump"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
ferrium_part = 10

[[recipes]]
id = "electric_mining_rig_mk2"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
portable_originium_rig = 1
ferrium_ore = 10

[[recipes]]
id = "refining_unit"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
originium_ore = 5

[[recipes]]
id = "shredding_unit"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
origocrust = 5

[[recipes]]
id = "fitting_unit"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
origocrust = 10

[[recipes]]
id = "moulding_unit"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
origocrust = 10

[[recipes]]
id = "planting_unit"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
carbon = 10
amethyst_part = 20

[[recipes]]
id = "seed_picking_unit"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
amethyst_part = 20

[[recipes]]
id = "gearing_unit"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
origocrust = 10

[[recipes]]
id = "filling_unit"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
amethyst_part = 20

[[recipes]]
id = "packaging_unit"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
amethyst_part = 20

[[recipes]]
id = "reactor_crucible"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
ferrium_part = 20

[[recipes]]
id = "grinding_unit"
by = "crafting"
time = 0
out = 1
[recipes.inputs]
ferrium_part = 10

# --- Gathering ---

[[recipes]]
id = "buckflower"
by = "gathering"
time = 0
out = 1

[[recipes]]
id = "firebuckle"
by = "gathering"
time = 0
out = 1

[[recipes]]
id = "citrome"
by = "gathering"
time = 0
out = 1

[[recipes]]
id = "umbraline"
by = "gathering"
time = 0
out = 1

[[recipes]]
id = "sandleaf"
by = "gathering"
time = 0
out = 1

[[recipes]]
id = "aketine"
by = "gathering"
time = 0
out = 1

[[recipes]]
id = "jincao"
by = "gathering"
time = 0
out = 1

[[recipes]]
id = "yazhen"
by = "gathering"
time = 0
out = 1

[[recipes]]
id = "fluffed_jincao"
by = "gathering"
time = 0
out = 1

[[recipes]]
id = "thorny_yazhen"
by = "gathering"
time = 0
out = 1

[[recipes]]
id = "reed_rye"
by = "gathering"
time = 0
out = 1

[[recipes]]
id = "tartpepper"
by = "gathering"
time = 0
out = 1

[[recipes]]
id = "rejade_ginseng"
by = "gathering"
time = 0
out = 1

[[recipes]]
id = "amber_rice"
by = "gathering"
time = 0
out = 1

[[recipes]]
id = "wood"
by = "gathering"
time = 0
out = 1

# --- Resourcing ---

# --- Mining Rig ---

[[recipes]]
id = "originium_ore"
by = "portable_originium_rig"
time = 2
out = 1
is_source = true

[[recipes]]
id = "originium_ore"
by = "electric_mining_rig"
time = 2
out = 1
is_source = true

[[recipes]]
id = "originium_ore"
by = "electric_mining_rig_mk2"
time = 2
out = 1
is_source = true

[[recipes]]
id = "amethyst_ore"
by = "electric_mining_rig"
time = 2
out = 1
is_source = true

[[recipes]]
id = "amethyst_ore"
by = "electric_mining_rig_mk2"
time = 2
out = 1
is_source = true

[[recipes]]
id = "ferrium_ore"
by = "electric_mining_rig_mk2"
time = 2
out = 1
is_source = true

# --- Fluid Pump

[[recipes]]
id = "clean_water"
by = "fluid_pump"
time = 1
out = 1
is_source = true

[[recipes]]
id = "jincao_solution"
by = "fluid_pump"
time = 1
out = 1

[[recipes]]
id = "yazhen_solution"
by = "fluid_pump"
time = 1
out = 1

# --- Processing ---

# --- Refining Unit ---

[[recipes]]
id = "origocrust"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
originium_ore = 1

[[recipes]]
id = "origocrust"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
origocrust_powder = 1

[[recipes]]
id = "amethyst_fiber"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
amethyst_ore = 1

[[recipes]]
id = "amethyst_fiber"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
amethyst_powder = 1

[[recipes]]
id = "ferrium"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
ferrium_ore = 1

[[recipes]]
id = "ferrium"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
ferrium_powder = 1

[[recipes]]
id = "origocrust_powder"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
originium_powder = 1

[[recipes]]
id = "carbon"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
wood = 1

[[recipes]]
id = "carbon"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
buckflower = 1

[[recipes]]
id = "carbon"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
citrome = 1

[[recipes]]
id = "carbon"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
sandleaf = 1

[[recipes]]
id = "carbon"
by = "refining_unit"
time = 2
out = 2
[recipes.inputs]
jincao = 1

[[recipes]]
id = "carbon"
by = "refining_unit"
time = 2
out = 2
[recipes.inputs]
yazhen = 1

[[recipes]]
id = "carbon_powder"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
buckflower_powder = 1

[[recipes]]
id = "carbon_powder"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
citrome_powder = 1

[[recipes]]
id = "carbon_powder"
by = "refining_unit"
time = 2
out = 2
[recipes.inputs]
sandleaf_powder = 3

[[recipes]]
id = "carbon_powder"
by = "refining_unit"
time = 2
out = 2
[recipes.inputs]
jincao_powder = 1

[[recipes]]
id = "carbon_powder"
by = "refining_unit"
time = 2
out = 2
[recipes.inputs]
yazhen_powder = 1

[[recipes]]
id = "dense_origocrust_powder"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
dense_originium_powder = 1

[[recipes]]
id = "packed_origocrust"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
dense_origocrust_powder = 1

[[recipes]]
id = "cryston_fiber"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
cryston_powder = 1

[[recipes]]
id = "steel"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
dense_ferrium_powder = 1

[[recipes]]
id = "dense_carbon_powder"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
ground_buckflower_powder = 1

[[recipes]]
id = "dense_carbon_powder"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
ground_citrome_powder = 1

[[recipes]]
id = "stabilized_carbon"
by = "refining_unit"
time = 2
out = 1
[recipes.inputs]
dense_carbon_powder = 1

# --- Shredding Unit ---

[[recipes]]
id = "originium_powder"
by = "shredding_unit"
time = 2
out = 1
[recipes.inputs]
originium_ore = 1

[[recipes]]
id = "origocrust_powder"
by = "shredding_unit"
time = 2
out = 1
[recipes.inputs]
origocrust = 1

[[recipes]]
id = "amethyst_powder"
by = "shredding_unit"
time = 2
out = 1
[recipes.inputs]
amethyst_ore = 1

[[recipes]]
id = "ferrium_powder"
by = "shredding_unit"
time = 2
out = 1
[recipes.inputs]
ferrium = 1

[[recipes]]
id = "carbon_powder"
by = "shredding_unit"
time = 2
out = 2
[recipes.inputs]
carbon = 1

[[recipes]]
id = "buckflower_powder"
by = "shredding_unit"
time = 2
out = 2
[recipes.inputs]
buckflower = 1

[[recipes]]
id = "citrome_powder"
by = "shredding_unit"
time = 2
out = 2
[recipes.inputs]
citrome = 1

[[recipes]]
id = "sandleaf_powder"
by = "shredding_unit"
time = 2
out = 3
[recipes.inputs]
sandleaf = 1

[[recipes]]
id = "jincao_powder"
by = "shredding_unit"
time = 2
out = 2
[recipes.inputs]
jincao = 1

[[recipes]]
id = "yazhen_powder"
by = "shredding_unit"
time = 2
out = 2
[recipes.inputs]
yazhen = 1

# --- Fitting Unit ---

[[recipes]]
id = "amethyst_part"
by = "fitting_unit"
time = 2
out = 1
[recipes.inputs]
amethyst_fiber = 1

[[recipes]]
id = "cryston_part"
by = "fitting_unit"
time = 2
out = 1
[recipes.inputs]
cryston_fiber = 1

[[recipes]]
id = "ferrium_part"
by = "fitting_unit"
time = 2
out = 1
[recipes.inputs]
ferrium = 1

[[recipes]]
id = "steel_part"
by = "fitting_unit"
time = 2
out = 1
[recipes.inputs]
steel = 1

# --- Moulding Unit ---

[[recipes]]
id = "amethyst_bottle"
by = "moulding_unit"
time = 2
out = 1
[recipes.inputs]
amethyst_fiber = 2

[[recipes]]
id = "cryston_bottle"
by = "moulding_unit"
time = 2
out = 1
[recipes.inputs]
cryston_fiber = 2

[[recipes]]
id = "ferrium_bottle"
by = "moulding_unit"
time = 2
out = 1
[recipes.inputs]
ferrium = 2

[[recipes]]
id = "steel_bottle"
by = "moulding_unit"
time = 2
out = 1
[recipes.inputs]
steel = 2

# ---Planting Unit (Solid Mode)---

[[recipes]]
id = "buckflower"
by = "planting_unit"
time = 2
out = 1
[recipes.inputs]
buckflower_seed = 1

[[recipes]]
id = "citrome"
by = "planting_unit"
time = 2
out = 1
[recipes.inputs]
citrome_seed = 1

[[recipes]]
id = "sandleaf"
by = "planting_unit"
time = 2
out = 1
[recipes.inputs]
sandleaf_seed = 1

[[recipes]]
id = "aketine"
by = "planting_unit"
time = 2
out = 1
[recipes.inputs]
aketine_seed = 1

# --- Planting Unit (Fluid Mode) ---
[[recipes]]
id = "jincao"
by = "planting_unit"
time = 2
out = 2
[recipes.inputs]
clean_water = 1
jincao_seed = 1

[[recipes]]
id = "yazhen"
by = "planting_unit"
time = 2
out = 2
[recipes.inputs]
clean_water = 1
yazhen_seed = 1

# --- Seed-Picking Unit ---

[[recipes]]
id = "buckflower_seed"
by = "seed_picking_unit"
time = 2
out = 2
is_source = true
[recipes.inputs]
buckflower = 1

[[recipes]]
id = "citrome_seed"
by = "seed_picking_unit"
time = 2
out = 2
is_source = true
[recipes.inputs]
citrome = 1

[[recipes]]
id = "sandleaf_seed"
by = "seed_picking_unit"
time = 2
out = 2
is_source = true
[recipes.inputs]
sandleaf = 1

[[recipes]]
id = "aketine_seed"
by = "seed_picking_unit"
time = 2
out = 2
is_source = true
[recipes.inputs]
aketine = 1

[[recipes]]
id = "jincao_seed"
by = "seed_picking_unit"
time = 2
out = 1
is_source = true
[recipes.inputs]
jincao = 1

[[recipes]]
id = "yazhen_seed"
by = "seed_picking_unit"
time = 2
out = 1
is_source = true
[recipes.inputs]
yazhen = 1

[[recipes]]
id = "amber_rice_seed"
by = "seed_picking_unit"
time = 2
out = 2
is_source = true
[recipes.inputs]
amber_rice = 1

[[recipes]]
id = "reed_rye_seed"
by = "seed_picking_unit"
time = 2
out = 2
is_source = true
[recipes.inputs]
reed_rye = 1

[[recipes]]
id = "tartpepper_seed"
by = "seed_picking_unit"
time = 2
out = 2
is_source = true
[recipes.inputs]
tartpepper = 1

# --- Forge of the Sky ---

[[recipes]]
id = "xiranite"
by = "forge_of_the_sky"
time = 2
out = 1
[recipes.inputs]
clean_water = 1
stabilized_carbon = 2

[[recipes]]
id = "bumper_rich"
by = "forge_of_the_sky"
time = 2
out = 1
[recipes.inputs]
liquid_xiranite = 1
burdo_muck = 1

# --- Assembly ---

# --- Gearing Unit ---

[[recipes]]
id = "amethyst_component"
by = "gearing_unit"
time = 10
out = 1
[recipes.inputs]
amethyst_fiber = 5
origocrust = 5

[[recipes]]
id = "ferrium_component"
by = "gearing_unit"
time = 10
out = 1
[recipes.inputs]
ferrium = 10
origocrust = 10

[[recipes]]
id = "cryston_component"
by = "gearing_unit"
time = 10
out = 1
[recipes.inputs]
cryston_fiber = 10
packed_origocrust = 10

[[recipes]]
id = "xiranite_component"
by = "gearing_unit"
time = 10
out = 1
[recipes.inputs]
xiranite = 10
packed_origocrust = 10

# --- Filling Unit (Solid Mode)---

[[recipes]]
id = "buck_capsule_c"
by = "filling_unit"
time = 10
out = 1
[recipes.inputs]
buckflower_powder = 5
amethyst_bottle = 5

[[recipes]]
id = "buck_capsule_b"
by = "filling_unit"
time = 10
out = 1
[recipes.inputs]
buckflower_powder = 10
ferrium_bottle = 10

[[recipes]]
id = "buck_capsule_a"
by = "filling_unit"
time = 10
out = 1
[recipes.inputs]
ground_buckflower_powder = 10
steel_bottle = 10

[[recipes]]
id = "canned_citrome_c"
by = "filling_unit"
time = 10
out = 1
[recipes.inputs]
citrome_powder = 5
amethyst_bottle = 5

[[recipes]]
id = "canned_citrome_b"
by = "filling_unit"
time = 10
out = 1
[recipes.inputs]
citrome_powder = 10
ferrium_bottle = 10

[[recipes]]
id = "canned_citrome_a"
by = "filling_unit"
time = 10
out = 1
[recipes.inputs]
ground_citrome_powder = 10
steel_bottle = 10

# --- Filling Unit (Fluid Mode)---

[[recipes]]
id = "amethyst_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
clean_water = 1
amethyst_bottle = 1

[[recipes]]
id = "amethyst_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
jincao_solution = 1
amethyst_bottle = 1

[[recipes]]
id = "amethyst_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
yazhen_solution = 1
amethyst_bottle = 1

[[recipes]]
id = "amethyst_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
liquid_xiranite = 1
amethyst_bottle = 1

[[recipes]]
id = "ferrium_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
clean_water = 1
ferrium_bottle = 1

[[recipes]]
id = "ferrium_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
jincao_solution = 1
ferrium_bottle = 1

[[recipes]]
id = "ferrium_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
yazhen_solution = 1
ferrium_bottle = 1

[[recipes]]
id = "ferrium_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
liquid_xiranite = 1
ferrium_bottle = 1

[[recipes]]
id = "cryston_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
clean_water = 1
cryston_bottle = 1

[[recipes]]
id = "cryston_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
jincao_solution = 1
cryston_bottle = 1

[[recipes]]
id = "cryston_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
yazhen_solution = 1
cryston_bottle = 1

[[recipes]]
id = "cryston_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
liquid_xiranite = 1
cryston_bottle = 1

[[recipes]]
id = "steel_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
clean_water = 1
steel_bottle = 1

[[recipes]]
id = "steel_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
jincao_solution = 1
steel_bottle = 1

[[recipes]]
id = "steel_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
yazhen_solution = 1
steel_bottle = 1

[[recipes]]
id = "steel_bottle"
by = "filling_unit"
time = 2
out = 1
[recipes.inputs]
liquid_xiranite = 1
steel_bottle = 1

# --- Packaging Unit ---

[[recipes]]
id = "lc_valley_battery"
by = "packaging_unit"
time = 10
out = 1
[recipes.inputs]
originium_powder = 10
amethyst_part = 5

[[recipes]]
id = "sc_valley_battery"
by = "packaging_unit"
time = 10
out = 1
[recipes.inputs]
originium_powder = 15
ferrium_part = 10

[[recipes]]
id = "hc_valley_battery"
by = "packaging_unit"
time = 10
out = 1
[recipes.inputs]
dense_originium_powder = 15
steel_part = 10

[[recipes]]
id = "lc_wuling_battery"
by = "packaging_unit"
time = 10
out = 1
[recipes.inputs]
dense_originium_powder = 15
xiranite = 5

[[recipes]]
id = "industrial_explosive"
by = "packaging_unit"
time = 10
out = 1
[recipes.inputs]
aketine_powder = 1
amethyst_part = 5

[[recipes]]
id = "jincao_drink"
by = "packaging_unit"
time = 10
out = 1
[recipes.inputs]
ferrium_bottle = 5
amethyst_part = 10

[[recipes]]
id = "yazhen_syringe_c"
by = "packaging_unit"
time = 10
out = 1
[recipes.inputs]
ferrium_bottle = 5
amethyst_part = 10

# --- Reactor Crucible ---

[[recipes]]
id = "jincao_solution"
by = "reactor_crucible"
time = 2
out = 1
[recipes.inputs]
clean_water = 1
jincao_powder = 1

[[recipes]]
id = "yazhen_solution"
by = "reactor_crucible"
time = 2
out = 1
[recipes.inputs]
clean_water = 1
yazhen_powder = 1

[[recipes]]
id = "liquid_xiranite"
by = "reactor_crucible"
time = 2
out = 1
[recipes.inputs]
clean_water = 1
xiranite = 1

# --- Grinding Unit ---

[[recipes]]
id = "dense_originium_powder"
by = "grinding_unit"
time = 2
out = 1
[recipes.inputs]
sandleaf_powder = 1
originium_powder = 2

[[recipes]]
id = "dense_origocrust_powder"
by = "grinding_unit"
time = 2
out = 1
[recipes.inputs]
sandleaf_powder = 1
origocrust_powder = 2

[[recipes]]
id = "cryston_powder"
by = "grinding_unit"
time = 2
out = 1
[recipes.inputs]
sandleaf_powder = 1
amethyst_powder = 2

[[recipes]]
id = "dense_ferrium_powder"
by = "grinding_unit"
time = 2
out = 1
[recipes.inputs]
sandleaf_powder = 1
ferrium_powder = 2

[[recipes]]
id = "dense_carbon_powder"
by = "grinding_unit"
time = 2
out = 1
[recipes.inputs]
sandleaf_powder = 1
carbon_powder = 2

[[recipes]]
id = "ground_buckflower_powder"
by = "grinding_unit"
time = 2
out = 1
[recipes.inputs]
sandleaf_powder = 1
buckflower_powder = 2

[[recipes]]
id = "ground_citrome_powder"
by = "grinding_unit"
time = 2
out = 1
[recipes.inputs]
sandleaf_powder = 1
citrome_powder = 2

# --- Generator ---

[[recipes]]
id = "power"
by = "generator"
time = 8
out = 50
[recipes.inputs]
originium = 1

[[recipes]]
id = "power"
by = "generator"
time = 40
out = 220
[recipes.inputs]
lc_valley_battery = 1

[[recipes]]
id = "power"
by = "generator"
time = 40
out = 420
[recipes.inputs]
sc_valley_battery = 1

[[recipes]]
id = "power"
by = "generator"
time = 40
out = 1100
[recipes.inputs]
hc_valley_battery = 1

[[recipes]]
id = "power"
by = "generator"
time = 40
out = 1600
[recipes.inputs]
lc_wuling_battery = 1
